sudo: false
language: node_js
services:
- elasticsearch
before_script:
  - sleep 10
node_js:
  - '6'
  - '8'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
